name: Release CLI

on:
  push:
    branches:
      - main
    paths:
      - 'cli/so/**'

permissions:
  contents: write # Needed for creating releases
  packages: write # Needed for pushing to registries

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli/so  # Set default working directory for all run steps
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for GoReleaser to generate changelogs

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: cli/so

      - name: Run all checks
        run: make all

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          working-directory: cli/so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}