name: Release CLI

on:
  push:
    branches:
      - main
    paths:
      - 'cli/so/**'

permissions:
  contents: write # Needed for creating releases
  packages: write # Needed for pushing to registries
  pull-requests: write # Needed for semantic-release

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli/so
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for GoReleaser to generate changelogs
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: cli/so

      - name: Run all checks
        run: make all

      - name: Setup semantic-release
        run: |
          echo '{
            "branches": ["main"],
            "tagFormat": "cli/v${version}",
            "plugins": [
              ["@semantic-release/commit-analyzer", {
                "preset": "conventionalcommits",
                "releaseRules": [
                  {"type": "feat", "release": "minor"},
                  {"type": "fix", "release": "patch"},
                  {"type": "docs", "release": "patch"},
                  {"type": "style", "release": "patch"},
                  {"type": "refactor", "release": "patch"},
                  {"type": "perf", "release": "patch"},
                  {"type": "test", "release": "patch"}
                ]
              }]
            ]
          }' > .releaserc.json

      - name: Create Release Tag
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: true
          allow-initial-development-versions: true
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          version: v2.9  # Use newer version that supports config v2
          args: release --clean
          workdir: cli/so